### ISSUE TITLE
H3Worldmap: selectProjection() selectProjectionFn(): factor out into a lit component

### ISSUE THREAD

**Issue by rudifa** [olange/h3-worldmap#12] opened 2022-04-15 17:20 UTC
`H3Worldmap selectProjection() selectProjectionFn()`: factor out into a lit component
Also move `AVAILABLE_PROJECTIONS` map into a separate file to make it available to components using it

**Comment by rudifa** [comment] 2022-04-19 13:46
RE: _H3Worldmap selectProjection() selectProjectionFn(): factor out into a lit component_ (and create a separate `dropdown-menu` component): proposed in PR#14

RE: _H3Worldmap selectProjection() selectProjectionFn(): factor out into a lit component_: proposed in PR#15

**Comment by olange** [comment] 2022-04-29 10:27
This is a duplicate of #3, I am therefore closing this one. The above mentioned changes have been partially contributed by PR #1 and and PR #21, and will be completed with PR #14.

**Closed by olange** 2022-04-29 10:27 UTC
Labels: duplicate
